# Importing Data Sets

### Importing a CSV into Python

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

# use read_csv to read the daat from the URL and store it in a DataFram

df = pd.read_csv(url)

# read_csv assumes the data contains a header

# Importing a csv without a header 
# if you data has no header, we need to assign headers by setting header to None

df = pd.read_csv(url, header=None)

### Printing the dataframe

- **df** prints the entire dataframe (not recommended for larger datasets)
- **df.head(n)** to show the first n rows of data frame
- **df.tail(n)** to show the bottom n rows of data frame

In [7]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S

### Adding headers
- Replace default headers (by df.columns = headers)

In [8]:
headers = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"]

df.columns = headers

df.head(5)

,a,b,c,d,e,f,g,h,i,j,k,l
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S

### Exporting a Pandas dataframe to CSV
- Preserve progress anytime by saving modified dataset using

In [13]:
path = r"C:\Users\PMLS\Downloads\dataimportpractice.csv"
df.to_csv(path)

<img src="assets/02_reading_and_saving_data.jpg" width="600">

# Basic Insights from the data

- It is important to understand your data before you begin any analysis
- You should check:
  - Data Types 
  - Data Distribution
- Locate potential issues with the data