# Importing Data Sets

### Importing a CSV into Python

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

# use read_csv to read the daat from the URL and store it in a DataFram

df = pd.read_csv(url)

# read_csv assumes the data contains a header

# Importing a csv without a header 
# if you data has no header, we need to assign headers by setting header to None

df = pd.read_csv(url, header=None)

### Printing the dataframe

- **df** prints the entire dataframe (not recommended for larger datasets)
- **df.head(n)** to show the first n rows of data frame
- **df.tail(n)** to show the bottom n rows of data frame

In [7]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S

### Adding headers
- Replace default headers (by df.columns = headers)

In [8]:
headers = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"]

df.columns = headers

df.head(5)

,a,b,c,d,e,f,g,h,i,j,k,l
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S

### Exporting a Pandas dataframe to CSV
- Preserve progress anytime by saving modified dataset using

In [9]:
path = r"C:\Users\PMLS\Downloads\dataimportpractice.csv"
df.to_csv(path)

<img src="assets/02_reading_and_saving_data.jpg" width="750">

# Basic Insights from the data

- It is important to understand your data before you begin any analysis
- You should check:
  - Data Types 
  - Data Distribution
- Locate potential issues with the data

<p align="center">
  <img src="assets/03_dataset_data_types.jpg" width="750">
</p>

### Data types

We use `dataframe.datatypes` to check data types
When the data type method is applied to the dataset, the data type of each column is returned in a series

In [10]:
df.dtypes

a    object
b    object
c    object
d    object
e    object
f    object
g    object
h    object
i    object
j    object
k    object
l    object
dtype: object

### dataframe.describe()
- Returns a statistical summary of each column to learn about the distribution of data in each column. 
- The statistical metrics can tell the data scientist if there are mathematical issues that may exist like
   extreme outliers and large deviations
- Data frame descrive() function skips rows and columns that do not contains numbers, it is possible to make the described method  
  work for object type columns as well.

In [11]:
df.describe()

,a,b,c,d,e,f,g,h,i,j,k,l
count,892,892,892,892,892,715,892,892,892,892,205,890
unique,892,3,4,892,3,89,8,8,682,249,148,4
top,PassengerId,0,3,Name,male,24,0,0,CA. 2343,8.05,C23 C25 C27,S
freq,1,549,491,1,577,30,608,678,7,43,4,644

### dataframe.describe(inclule="all")

- It will provide full summary statistics
- now it will show summary of all columns including object type attriburtes

In [12]:
df.describe(include="all")

,a,b,c,d,e,f,g,h,i,j,k,l
count,892,892,892,892,892,715,892,892,892,892,205,890
unique,892,3,4,892,3,89,8,8,682,249,148,4
top,PassengerId,0,3,Name,male,24,0,0,CA. 2343,8.05,C23 C25 C27,S
freq,1,549,491,1,577,30,608,678,7,43,4,644

### info() function
dataframe.info() provides a concise summary of your DataFrame

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       892 non-null    object
 1   b       892 non-null    object
 2   c       892 non-null    object
 3   d       892 non-null    object
 4   e       892 non-null    object
 5   f       715 non-null    object
 6   g       892 non-null    object
 7   h       892 non-null    object
 8   i       892 non-null    object
 9   j       892 non-null    object
 10  k       205 non-null    object
 11  l       890 non-null    object
dtypes: object(12)
memory usage: 83.8+ KB